apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-server-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: test-server.raghiba.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-server-service
            port:
              number: 80
  tls:
  - hosts:
    - test-server.raghiba.com
    secretName: test-server-tls
