apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-service-ingress
  namespace: test-http-server
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-http01-prod"
spec:
  rules:
  - host: test-service.raghiba.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-service
            port:
              number: 80
  tls:
  - hosts:
    - test-service.raghiba.com
    secretName: test-service-tls
