name: Deploy to K3s
on:
  push:
    branches: [ "main" ] # Or your main development branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up kubectl and deploy
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_SECRET }}
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml -n test-http-server
          kubectl apply -f k8s/service.yaml -n test-http-server
          kubectl apply -f k8s/ingress.yaml -n test-http-server
